spring:
  datasource:
    driver-class-name: org.h2.Driver
    # DB_CLOSE_DELAY=-1 可能造成内存泄露  仅供演示使用
    url: jdbc:h2:mem:id_server;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  sql:
    init:
      # 初始化数据表 DDL
      schema-locations: classpath:sql/ddl.sql
      # 初始化数据 DML
      data-locations: classpath:sql/dml.sql
      mode: embedded
    h2:
      console:
        enabled: true
        settings:
          trace: true
          web-allow-others: true
        path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    org.springframework.web: trace
    org.springframework.security.oauth2: debug
    org.springframework.jdbc.core: debug
    org.springframework.security: trace